"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACHIEVEMENT_CATALOG = void 0;
exports.toAchievementModel = toAchievementModel;
exports.getAchievementBySlug = getAchievementBySlug;
exports.visibleAchievements = visibleAchievements;
exports.ACHIEVEMENT_CATALOG = [
    // ------------------------------------------------
    // USO — ferramentas (XP baixo)
    // ------------------------------------------------
    {
        slug: "primeira-copy",
        title: "Primeira Copy",
        description: "Gerou e salvou sua primeira copy.",
        category: "uso",
        xpReward: 10,
        threshold: 1,
        unit: "copy",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "copies_criadas",
    },
    {
        slug: "primeira-ideia",
        title: "Primeira Ideia",
        description: "Salvou a primeira ideia de conteúdo.",
        category: "uso",
        xpReward: 10,
        threshold: 1,
        unit: "ideia",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "ideias_salvas",
    },
    {
        slug: "primeiro-rascunho",
        title: "Primeiro Rascunho",
        description: "Montou o primeiro preview/rascunho.",
        category: "uso",
        xpReward: 10,
        threshold: 1,
        unit: "rascunho",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "drafts_criados",
    },
    {
        slug: "analista-em-acao",
        title: "Analista em Ação",
        description: "Rodou a análise de desempenho pela primeira vez.",
        category: "uso",
        xpReward: 10,
        threshold: 1,
        unit: "análise",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "analises_rodadas",
    },
    // ------------------------------------------------
    // CONSISTÊNCIA — acompanhar resultados
    // ------------------------------------------------
    {
        slug: "primeira-semana-ativa",
        title: "Primeira Semana Ativa",
        description: "Usou o Inst Acessor com consistência durante uma semana.",
        category: "consistencia",
        xpReward: 20,
        threshold: 7,
        unit: "dias",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "primeira_semana_ativa",
    },
    {
        slug: "frequencia-consistente",
        title: "Frequência Consistente",
        description: "Registrou métricas em 3+ dias na mesma semana.",
        category: "consistencia",
        xpReward: 25,
        threshold: 3,
        unit: "dias",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "frequencia_consistente",
    },
    {
        slug: "snapshots-instagram",
        title: "Olho no Instagram",
        description: "Acumulou 5 sincronizações do Instagram.",
        category: "consistencia",
        xpReward: 30,
        threshold: 5,
        unit: "sincronizações",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "snapshots_instagram",
    },
    {
        slug: "snapshots-tiktok",
        title: "Olho no TikTok",
        description: "Acumulou 5 sincronizações do TikTok.",
        category: "consistencia",
        xpReward: 30,
        threshold: 5,
        unit: "sincronizações",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "snapshots_tiktok",
    },
    // ------------------------------------------------
    // ESTRATÉGIA — executar recomendações, testar, completar
    // ------------------------------------------------
    {
        slug: "recomendacao-executada",
        title: "Recomendação Executada",
        description: "Executou uma recomendação da Mentoria.",
        category: "estrategia",
        xpReward: 40,
        threshold: 1,
        unit: "recomendação",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "recomendacoes_aplicadas",
    },
    {
        slug: "experimento-completado",
        title: "Cientista do Crescimento",
        description: "Completou um experimento (confirmado ou rejeitado).",
        category: "estrategia",
        xpReward: 50,
        threshold: 1,
        unit: "experimento",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "experimentos_completados",
    },
    {
        slug: "perfil-completo",
        title: "Perfil Afiado",
        description: "Preencheu seu perfil de inteligência (nicho e objetivos).",
        category: "estrategia",
        xpReward: 15,
        threshold: 1,
        unit: "perfil",
        tier: "BRONZE",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "perfil_completo",
    },
    {
        slug: "metas-concluidas",
        title: "Meta Batida",
        description: "Concluiu sua primeira meta estratégica.",
        category: "estrategia",
        xpReward: 35,
        threshold: 1,
        unit: "meta",
        tier: "PRATA",
        hidden: false,
        version: 1,
        active: true,
        progressKind: "desafio_metas_concluidas",
    },
    // ------------------------------------------------
    // DESAFIOS — entram quando ~70% do conjunto for alcançado
    // ------------------------------------------------
    {
        slug: "desafio-nivel-5",
        title: "Desafio: Nível 5",
        description: "Alcançou o nível 5 de progressão.",
        category: "estrategia",
        xpReward: 60,
        threshold: 5,
        unit: "níveis",
        tier: "DESAFIO",
        hidden: true,
        version: 1,
        active: true,
        progressKind: "desafio_primeiro_nivel",
    },
    {
        slug: "desafio-maestria-xp",
        title: "Desafio: Mestre do XP",
        description: "Acumulou 1000 XP de progressão.",
        category: "estrategia",
        xpReward: 80,
        threshold: 1000,
        unit: "xp",
        tier: "DESAFIO",
        hidden: true,
        version: 1,
        active: true,
        progressKind: "desafio_maestria_xp",
    },
    {
        slug: "desafio-10-conquistas",
        title: "Desafio: Colecionador",
        description: "Desbloqueou 10 conquistas diferentes.",
        category: "estrategia",
        xpReward: 100,
        threshold: 10,
        unit: "conquistas",
        tier: "DESAFIO",
        hidden: true,
        version: 1,
        active: true,
        progressKind: "desafio_10_conquistas",
    },
];
/** Converte a definição para o model Prisma Achievement (sem progressKind). */
function toAchievementModel(def) {
    return {
        slug: def.slug,
        title: def.title,
        description: def.description,
        category: def.category,
        xpReward: def.xpReward,
        threshold: def.threshold,
        unit: def.unit,
        tier: def.tier,
        hidden: def.hidden,
        version: def.version,
        active: def.active,
    };
}
/** Busca uma definição por slug. */
function getAchievementBySlug(slug) {
    return exports.ACHIEVEMENT_CATALOG.find((a) => a.slug === slug);
}
/** Retorna as conquistas visíveis (não-hidden) — os desafios entram pós-70%. */
function visibleAchievements() {
    return exports.ACHIEVEMENT_CATALOG.filter((a) => !a.hidden);
}
