"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STREAK_BONUS_XP = exports.STREAK_BONUS_MILESTONES = exports.RITMO_PERIODS = exports.RITMO_KINDS = exports.RITMO_BANDS = exports.startOfMonth = exports.startOfWeek = exports.startOfDay = exports.streakBonusesGranted = exports.grantStreakBonuses = exports.computeStreak = exports.recomputeRitmo = exports.getRitmoState = exports.applySelfDisplayName = exports.setDisplayNameSource = exports.getDisplayNameInfo = exports.getEvolutionHistory = exports.getUserRankSummary = exports.getRanking = exports.GOAL_STATUSES = exports.GOAL_CATEGORIES = exports.recomputeGoalProgress = exports.deleteGoal = exports.updateGoal = exports.createGoal = exports.getGoal = exports.listGoals = exports.checkAndUnlockAchievements = exports.getUserAchievements = exports.seedAchievements = exports.computeProgress = exports.toAchievementModel = exports.visibleAchievements = exports.getAchievementBySlug = exports.ACHIEVEMENT_CATALOG = exports.getUserProgress = exports.grantXpAmount = exports.grantXp = exports.stableRefId = exports.levelInfoFromXp = exports.xpRequiredForLevel = exports.xpToNextLevel = exports.xpForSource = exports.XP_SOURCES = exports.XP_VALUES = exports.gp = void 0;
var db_1 = require("./db");
Object.defineProperty(exports, "gp", { enumerable: true, get: function () { return db_1.gp; } });
var xp_1 = require("./xp");
Object.defineProperty(exports, "XP_VALUES", { enumerable: true, get: function () { return xp_1.XP_VALUES; } });
Object.defineProperty(exports, "XP_SOURCES", { enumerable: true, get: function () { return xp_1.XP_SOURCES; } });
Object.defineProperty(exports, "xpForSource", { enumerable: true, get: function () { return xp_1.xpForSource; } });
Object.defineProperty(exports, "xpToNextLevel", { enumerable: true, get: function () { return xp_1.xpToNextLevel; } });
Object.defineProperty(exports, "xpRequiredForLevel", { enumerable: true, get: function () { return xp_1.xpRequiredForLevel; } });
Object.defineProperty(exports, "levelInfoFromXp", { enumerable: true, get: function () { return xp_1.levelInfoFromXp; } });
Object.defineProperty(exports, "stableRefId", { enumerable: true, get: function () { return xp_1.stableRefId; } });
Object.defineProperty(exports, "grantXp", { enumerable: true, get: function () { return xp_1.grantXp; } });
Object.defineProperty(exports, "grantXpAmount", { enumerable: true, get: function () { return xp_1.grantXpAmount; } });
Object.defineProperty(exports, "getUserProgress", { enumerable: true, get: function () { return xp_1.getUserProgress; } });
var achievements_1 = require("./achievements");
Object.defineProperty(exports, "ACHIEVEMENT_CATALOG", { enumerable: true, get: function () { return achievements_1.ACHIEVEMENT_CATALOG; } });
Object.defineProperty(exports, "getAchievementBySlug", { enumerable: true, get: function () { return achievements_1.getAchievementBySlug; } });
Object.defineProperty(exports, "visibleAchievements", { enumerable: true, get: function () { return achievements_1.visibleAchievements; } });
Object.defineProperty(exports, "toAchievementModel", { enumerable: true, get: function () { return achievements_1.toAchievementModel; } });
var progress_1 = require("./progress");
Object.defineProperty(exports, "computeProgress", { enumerable: true, get: function () { return progress_1.computeProgress; } });
Object.defineProperty(exports, "seedAchievements", { enumerable: true, get: function () { return progress_1.seedAchievements; } });
Object.defineProperty(exports, "getUserAchievements", { enumerable: true, get: function () { return progress_1.getUserAchievements; } });
Object.defineProperty(exports, "checkAndUnlockAchievements", { enumerable: true, get: function () { return progress_1.checkAndUnlockAchievements; } });
var goals_1 = require("./goals");
Object.defineProperty(exports, "listGoals", { enumerable: true, get: function () { return goals_1.listGoals; } });
Object.defineProperty(exports, "getGoal", { enumerable: true, get: function () { return goals_1.getGoal; } });
Object.defineProperty(exports, "createGoal", { enumerable: true, get: function () { return goals_1.createGoal; } });
Object.defineProperty(exports, "updateGoal", { enumerable: true, get: function () { return goals_1.updateGoal; } });
Object.defineProperty(exports, "deleteGoal", { enumerable: true, get: function () { return goals_1.deleteGoal; } });
Object.defineProperty(exports, "recomputeGoalProgress", { enumerable: true, get: function () { return goals_1.recomputeGoalProgress; } });
Object.defineProperty(exports, "GOAL_CATEGORIES", { enumerable: true, get: function () { return goals_1.GOAL_CATEGORIES; } });
Object.defineProperty(exports, "GOAL_STATUSES", { enumerable: true, get: function () { return goals_1.GOAL_STATUSES; } });
var ranking_1 = require("./ranking");
Object.defineProperty(exports, "getRanking", { enumerable: true, get: function () { return ranking_1.getRanking; } });
Object.defineProperty(exports, "getUserRankSummary", { enumerable: true, get: function () { return ranking_1.getUserRankSummary; } });
Object.defineProperty(exports, "getEvolutionHistory", { enumerable: true, get: function () { return ranking_1.getEvolutionHistory; } });
var display_name_1 = require("./display-name");
Object.defineProperty(exports, "getDisplayNameInfo", { enumerable: true, get: function () { return display_name_1.getDisplayNameInfo; } });
Object.defineProperty(exports, "setDisplayNameSource", { enumerable: true, get: function () { return display_name_1.setDisplayNameSource; } });
Object.defineProperty(exports, "applySelfDisplayName", { enumerable: true, get: function () { return display_name_1.applySelfDisplayName; } });
var momentum_1 = require("./momentum");
Object.defineProperty(exports, "getRitmoState", { enumerable: true, get: function () { return momentum_1.getRitmoState; } });
Object.defineProperty(exports, "recomputeRitmo", { enumerable: true, get: function () { return momentum_1.recomputeRitmo; } });
Object.defineProperty(exports, "computeStreak", { enumerable: true, get: function () { return momentum_1.computeStreak; } });
Object.defineProperty(exports, "grantStreakBonuses", { enumerable: true, get: function () { return momentum_1.grantStreakBonuses; } });
Object.defineProperty(exports, "streakBonusesGranted", { enumerable: true, get: function () { return momentum_1.streakBonusesGranted; } });
Object.defineProperty(exports, "startOfDay", { enumerable: true, get: function () { return momentum_1.startOfDay; } });
Object.defineProperty(exports, "startOfWeek", { enumerable: true, get: function () { return momentum_1.startOfWeek; } });
Object.defineProperty(exports, "startOfMonth", { enumerable: true, get: function () { return momentum_1.startOfMonth; } });
Object.defineProperty(exports, "RITMO_BANDS", { enumerable: true, get: function () { return momentum_1.RITMO_BANDS; } });
Object.defineProperty(exports, "RITMO_KINDS", { enumerable: true, get: function () { return momentum_1.RITMO_KINDS; } });
Object.defineProperty(exports, "RITMO_PERIODS", { enumerable: true, get: function () { return momentum_1.RITMO_PERIODS; } });
Object.defineProperty(exports, "STREAK_BONUS_MILESTONES", { enumerable: true, get: function () { return momentum_1.STREAK_BONUS_MILESTONES; } });
Object.defineProperty(exports, "STREAK_BONUS_XP", { enumerable: true, get: function () { return momentum_1.STREAK_BONUS_XP; } });
